# .github/workflows/receive-bump-netbeans-visual-diff-standalone.yml
name: "Auto-bump netbeans-visual-diff-standalone on dispatch"

on:
  repository_dispatch:
    types: [bump-netbeans-visual-diff-standalone]

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: Show payload for traceability
        run: |
          set -euo pipefail
          echo 'Incoming payload:'
          echo '${{ toJson(github.event.client_payload) }}'

      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Read current netbeans-visual-diff-standalone.version
        id: current
        run: |
          set -euo pipefail
          cur=$(grep -Eo '<netbeans-visual-diff-standalone\.version>[0-9A-Za-z._+-]+</netbeans-visual-diff-standalone\.version>' pom.xml | sed -E 's/.*<netbeans-visual-diff-standalone\.version>([^<]+)<\/netbeans-visual-diff-standalone\.version>.*/\1/' | head -n1)
          if [ -z "$cur" ]; then
            echo "Could not find <netbeans-visual-diff-standalone.version>…</netbeans-visual-diff-standalone.version> in pom.xml"
            exit 1
          fi
          echo "Detected old version: $cur"
          echo "version=$cur" >> "$GITHUB_OUTPUT"

      - name: Set netbeans-visual-diff-standalone.version to new value
        run: |
          set -euo pipefail
          mvn --no-transfer-progress -B versions:set-property \
            -Dproperty=netbeans-visual-diff-standalone.version \
            -DnewVersion='${{ github.event.client_payload.version }}' \
            -DgenerateBackupPoms=false

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_TOKEN }}
          branch: "bump-com.github.nbauma109-netbeans-visual-diff-standalone-${{ github.event.client_payload.version }}"
          commit-message: "Bump com.github.nbauma109:netbeans-visual-diff-standalone from ${{ steps.current.outputs.version }} to ${{ github.event.client_payload.version }}"
          title: "Bump com.github.nbauma109:netbeans-visual-diff-standalone from ${{ steps.current.outputs.version }} to ${{ github.event.client_payload.version }}"
          body: |
            Bumps com.github.nbauma109:netbeans-visual-diff-standalone from ${{ steps.current.outputs.version }} to ${{ github.event.client_payload.version }}.
          labels: |
            dependencies
            java
